---
- name: Darwin | Stop and disable tailscaled service (user-space)
  community.general.homebrew_services:
    name: "tailscale"
    state: absent

- name: Darwin | Remove Tailscale via Homebrew
  community.general.homebrew:
    name: "{{ tailscale_package }}"
    state: absent
    purge: true
