---
- name: Darwin | Stop and disable tailscaled service (user-space)
  ansible.builtin.command: brew services stop tailscale --user
  changed_when: false

- name: Darwin | Remove Tailscale via Homebrew
  community.general.homebrew:
    name: "{{ tailscale_package }}"
    state: absent
    purge: true
